---
name: dist

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install build dependencies
      run: pip install build
    - name: Build packages
      run: python -m build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
